language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
services:
  - rabbitmq
notifications:
  irc:
    - "irc.freenode.net#sensu"
script: "rspec . --tag ~ssl"
addons:
  code_climate:
    repo_token:629d024a848e2ebb1b0c0283c2046387c1b8c0d1cfd4d03289bef74a7b875d55
