sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.2.3
  - 2.3.0
  - jruby-9.0.5.0
services:
  - rabbitmq
  - redis
notifications:
  irc:
    - "irc.freenode.net#sensu"
script: "bundle exec rspec . --tag ~ssl"
